#!/usr/bin/python3
import sys
import os

import parse
import mutator
import thread_manager

from queue import Queue
from log import logger, CRASH_DIR

import timeit
import math

crashFile = 'bad.txt'

if '--crashfile' in sys.argv:
    index = sys.argv.index('--crashfile')
    crashFile = sys.argv[index + 1]
    
def handleCrash(crashInput: bytes) -> bool:
    global crashFile
    if crashInput is not None:
        logger.info("Found crash")
        with open(os.path.join(CRASH_DIR, crashFile), "wb") as badtxt:
            badtxt.write(crashInput)
        logger.info('Bad input written to ' + os.path.join(CRASH_DIR, crashFile))
        return True
    return False

def checkArgs():
    if len(sys.argv) < 3:
        logger.info(f"Usage: {sys.argv[0]} binaryfilename inputfilename")
        exit(0)

if __name__ == "__main__":
    checkArgs()

    binary = sys.argv[1]
    inputFileName = sys.argv[2]

    inputDict = parse.getDictFromInput(inputFileName)
    thread_manager.setBinary(binary)
    
    # run once with sample input to get runtime. timeout = 5+runtime
    # might be pointless because all the sample binaries run in << 1 second anyway
    t = timeit.timeit(stmt=f"sp.call('{binary}', stdin=fp, stdout=sp.DEVNULL, stderr=sp.DEVNULL)", setup=f"import subprocess as sp; fp=open('{inputFileName}', 'rb')", number=1)
    logger.info(f"runtime: {t}")
    runtime = math.ceil(t)

    logger.info('\nStarting fuzzer...')

    crashInput = thread_manager.fuzzMyLife(inputDict, runtime)
    if handleCrash(crashInput):
        logger.info("done")
    else:
        logger.info("failed :'(")